---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.4

suites:
  - name: duplicity-pkg
    run_list:
      - recipe[apt::default]
      - recipe[duplicity::default]
    attributes:
      duplicity:
        install_method: 'package'
  - name: duplicity-src
    run_list:
      - recipe[apt::default]
      - recipe[duplicity::default]
    attributes:
      duplicity:
        install_method: 'source'